baseURL: "https://ira-zibbu.github.io/"
title: Game of Life
paginate: 10
theme: hugo-PaperMod

params:
  defaultTheme: auto # to switch between dark or light according to browser theme

params:
    profileMode:
        enabled: true
        title: "Ira Zibbu" # optional default will be site title
        subtitle: "BS-MS at IISER Thiruvananthapuram | Incoming PhD student at University of Texas at Austin. I like thinking about evolution, microbes, genomes, computers and social justice. Named after the John Conway cellular automation model, not the Hasbro game."   
# imageUrl: "<image link>" # optional
       # imageTitle: "<title of image as alt>" # optional
        #imageWidth: 120 # custom size
       # imageHeight: 120 # custom size
        buttons:
            - name: Posts
              url: "/post"
           # - name: Github
           #   url: "https://github.com/"

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/ira-zibbu"
        - name: "Email"
          url: "ira.zibbu@gmail.com"
        - name: "Substack"
          url: "https://irazibbu.substack.com/"
        - name: "CV"
          url: "https://drive.google.com/file/d/1xGdIagndDkbe2JQ0lypCplTfL8hYaBft/view?usp=sharing"
        - name: "About Me"
          url: "https://ira-zibbu.github.io/post/whoami/"


